### ISSUE TITLE
docs: add proper documentation for README.md

### ISSUE THREAD

**Issue by iamdipanshusingh** [101Loop/APIManager-Flutter#2]

**Comment by nayakastha** [comment]
Hey! Can you assign this issue to me? Once you just tell me the aim of the project, I can prepare a good enough documentation in the README.md

**Comment by iamdipanshusingh** [comment]
Hi @nayakastha,

Thanks for showing interest in this project.
The aim of this project is simply to reduce the time in integrating the APIs and also reduce token management all of these from a single place. 
So, this library will work as a wrapper with a bit of abstraction and the user will only need to call a few methods.
I've added some feature points, I'm gonna be implementing soon. You can get a bit of ideas from there as well.
Let me know if any further input is needed from my side.
Assigning this to you :slightly_smiling_face:

**Comment by iamdipanshusingh** [comment]
Hey @nayakastha,

I have added `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` Plz add a link to them in `README.md`.
And have a look at [CONTRIBUTING.md](https://github.com/101Loop/APIManager-Flutter/blob/master/CONTRIBUTING.md) for a guide in working with forked repo, if needed

**Comment by nayakastha** [comment]
Sure Sure
