### ISSUE TITLE
create Pull Request template

### ISSUE THREAD

**Issue by iamdipanshusingh** [101Loop/APIManager-Flutter#20]
Whoever is reading this, plz note that I need a detailed PR template asking for:
- why this change is required
- is this tested, how?
- will this affect any functionality?
- is this backward compatible?

something like this and in detail... this is just an example... and plz ask to contribute first... I'll assign it to you, otherwise it might get assigned to someone else or maybe I'll do it myself, which will result in wasting your own time :slightly_smiling_face: So plz do LMK before doing it

Thanks

**Comment by ruddha2001** [comment]
Hello @iamdipanshusingh 
I would like to take this up. Can I be assigned for this?

**Comment by Mastersam07** [comment]
@iamdipanshusingh can this be assigned to me?

**Comment by iamdipanshusingh** [comment]
@Mastersam07 sure, assigning this to you.. plz LMK if you need to know anything about this

**Comment by Mastersam07** [comment]
@iamdipanshusingh I have sent in a pull request #30

**Comment by iamdipanshusingh** [comment]
@Mastersam07 thanx for raising this... and it LGTM I'll review it soon and will merge it as well... looks nice... LMK if you want to contribute any further
