### ISSUE TITLE
Enhancement: Handle sending body in delete method 

### ISSUE THREAD

**Issue by harshkc** [101Loop/APIManager-Flutter#25]
https://github.com/101Loop/APIManager-Flutter/blob/c5dc2cd3a3c9de29a49b19691eec07862caaa9dc/lib/src/api_manager.dart#L120

Enhancement Suggestion: 
- Handle sending body with delete requests which `http.client` out of the box don't allow.
 This will help users of the package to get that functionality out of the box and it will also help in making it a one-stop solution for all API management demands.

**Comment by iamdipanshusingh** [comment]
@harshkc this does not sound valid to me, why would anyone send the body in delete requests.. :sweat_smile: 
Closing this issue!
