### ISSUE TITLE
Make the README.md creative - with installation guide

### ISSUE THREAD

**Issue by iamdipanshusingh** [101Loop/APIManager-Flutter#29]
- need the README.md a bit informative - having some installation guide, how to use and all

**Comment by Mastersam07** [comment]
@iamdipanshusingh  Reading through the repo code and pubspec.yaml, this is a flutter package. How do you want the readme? Installation process on how to use the package?

I feel an example app would also be helpful. Let me know your thoughts.

**Comment by iamdipanshusingh** [comment]
@Mastersam07 yes, I need it something like that... 

Actually, there was an example app as well... but I have deleted it... 
I have changed my mind and I'm letting the users use it as they want... cuz they must be testing it with their own server's APIs and handling it will become a bit trickier and so, I won't be committing the `example` app fro now... but yes... we can do that in future :grinning:

**Comment by Mastersam07** [comment]
At the moment since the package have not been made live to pub.dev, then the installation in dependencies would be as shown below:

```
APIManager-Flutter:
    git:
      url: https://github.com/101Loop/APIManager-Flutter.git
      ref: master
```

You could assign this to me and I would look into it

**Comment by iamdipanshusingh** [comment]
@Mastersam07 yes exactly... but the package is `flutter_api_manager` :sweat_smile: 
Assigning this to you!

**Comment by Mastersam07** [comment]
Okay. Would work on it 😄

**Comment by iamdipanshusingh** [comment]
@Mastersam07 any update?? been 3 weeks now... :sweat_smile:

**Comment by Mastersam07** [comment]
Hey, somehow I forgot. I will send a PR soon.

**Comment by iamdipanshusingh** [comment]
sure, don't forget to update your fork
