### ISSUE TITLE
Storing sensitive data in shared preferences

### ISSUE THREAD

**Issue by harshkc** [101Loop/APIManager-Flutter#9]
The package description itself indicates that "**this plugin(shared preferences) must not be used for storing critical data**". It is best fitted for in-app preferences.
Suggestion:
_Flutter secure storage or encrypted hive box could be used to store the sensitive data._

**Comment by iamdipanshusingh** [comment]
@harshkc this is worth mentioning the point.
Right now, I don't wanna be dependent on any 3rd party plugins or packages you mentioned above. Will try to add this feature as well.
Thnx for mentioning that!

**Comment by iamdipanshusingh** [comment]
@harshkc I've added this point in the features list in `README.md`

**Comment by iamdipanshusingh** [comment]
@harshkc haven't found anything relevant to this... so I'll be taking your suggestion and will implement `flutter_secure_storage` instead. 
It'll get complicated for me to do the encryption part... and if by any chance I got that working on my own... I'll create a separate library for it... :sweat_smile:
